### ISSUE TITLE
Загрузка геометрии

### ISSUE THREAD

**Issue by askryshchenko** [ReptoidBusters/object-detection#2]
Создать модуль для загрузки .obj файлов. Необходимо осуществить загрузку вершин и поверхностей.

**Comment by ArtyomLobanov** [comment]
Simple parser, which read only geometry points and faces, is ready

**Comment by askryshchenko** [comment]
Не закрывай ишью до вмердживания пул реквеста, связанного с ним

**Comment by ArtyomLobanov** [comment]
Исправил указанные недочёты.

**Comment by ArtyomLobanov** [comment]
Добавил функцию load_object(path) -> Object3D.
Переделал устройство Object3D
